image: python:3.8.2

stages:
  - build
  - test

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8

services:
  - name: mongo:latest
    alias: mongo

Availability Service Test:
  stage: test
  script:
    - echo "Testing availability Service"
    - cd Booking/availability-service
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest test/