image: python:3.8-slim

stages:
  - build
  - test

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8


availability_service_test:
  stage: test
  tags:
    - docker
  script:
    - echo "Testing Availability Service"
    - cd availability-service
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest test/
