image: python:3.8

stages:
  - build
  - test

before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - apt-get update -qy
  - apt-get install -y python3-venv
  - python -m venv venv
  - source venv/bin/activate

services:
  - name: mongo:latest
    alias: mongo

test:
  stage: test
  script:
    - echo "Testing availability Service"
    - cd Booking/availability-service
    - pip install -r requirements.txt
    - pytest test/